#!/bin/bash
if [ ! "$1" ]
then
  echo "Please specify time frame i.e. \"2 weeks ago\""
  exit 1
fi
journalctl -u transmission --since "$*" | grep TR_TORRENT_NAME | cut -d' ' -f1-3,8 | sed 's/TR_TORRENT_NAME=//'
