---
- hosts: media
  roles:
  - { role: test,           tags: test }
  - { role: nfs,            tags: nfs }
  - { role: mounts,         tags: mounts }
  - { role: mediashares,    tags: mediashares }
  - { role: transmission,   tags: transmission }
  - { role: expressvpn,     tags: expressvpn }
  - { role: fauust.mariadb, become: true, tags: db }
