---
- name: configure swappiness
  ansible.builtin.sysctl:
    name:  vm.swappiness
    value: "{{swappiness}}"
    state: "present"
    reload: true
  become: true

- name: see if swapfile exists
  ansible.builtin.stat:
    path:   "{{swapfilePath}}"
  register: swap

- name: create swap
  include_tasks: create.yml
  when: (swapEnable|bool is true) and (not swap.stat.exists)

- name: remove swap
  include_tasks: remove.yml
  when: (swapEnable|bool is false) and (swap.stat.exists)
