---
- name: create directory
  ansible.builtin.file:
    path:  "{{mediaOtherShare}}"
    state: directory

- name: configure exports
  ansible.builtin.template:
    src:   other.exports
    dest:  /etc/exports.d/
    owner: root
    group: root
    mode:  0644
  become: true
  notify:
    - reload nfs
