---
timezone: "America/Toronto"
tzShort: EST

siteDomain:     "home.arpa"
siteGateway:    "192.168.0.1"
siteNetmask:    "255.255.255.0"
siteDNS:        "192.168.0.2"

mediaClients:
- "{{ query('community.general.dig', 'desktop'   )[0] }}"
- "{{ query('community.general.dig', 'phone'     )[0] }}"
- "{{ query('community.general.dig', 'ebox-haut' )[0] }}"
- "{{ query('community.general.dig', 'ebox-bas'  )[0] }}"
- "{{ query('community.general.dig', 'laptop'    )[0] }}"
