---
- name: disable dnsmasq
  ansible.builtin.systemd:
    name:    dnsmasq
    state:   stopped
    enabled: false
  become: true

- name: create docker container
  community.docker.docker_container:
    name:  pihole
    image: pihole/pihole
    restart_policy: unless-stopped
    #network_mode: host
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp" # for DHCP
    - "80:80/tcp"
    env:
      TZ: "{{timezone}}"
      WEBPASSWORD: "{{secretInfraPassword}}"
      FTLCONF_LOCAL_IPV4: "{{ansible_default_ipv4.address}}"
      PIHOLE_DNS_: "8.8.8.8;8.8.4.4"
    capabilities:
      - net_admin

- name: check pihole container
  ansible.builtin.uri:
    url: "http://{{inventory_hostname}}/admin"
  register: result
  until: result.status == 200
  retries: 10
  delay: 5
