---
- name: create docker container
  community.docker.docker_container:
    name:  pihole
    image: pihole/pihole
    restart_policy: unless-stopped
    ports:
    - "53/tcp:53/tcp"
    - "53/udp:53/udp"
    - 8001:80
    env:
      TZ: "{{timezone}}"
      WEBPASSWORD: "{{secretInfraPassword}}"
      FTLCONF_LOCAL_IPV4: "{{ansible_default_ipv4.address}}"
      PIHOLE_DNS_: "8.8.8.8;8.8.4.4"

- name: check pihole container
  ansible.builtin.uri:
    url: "http://{{ansible_hostname}}:8001/admin"
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: wrap up
  ansible.builtin.debug:
    msg: "Pihole admin: http://{{ansible_hostname}}:8001/admin"
