---
- name: create directories
  ansible.builtin.file:
    path:  "{{ item }}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
  with_items: "{{ mediaShares }}"
  become: true
 
- name: configure exports
  ansible.builtin.template:
    src:   mediashares.exports
    dest:  /etc/exports.d/
    owner: root
    group: root
    mode:  0644
  become: true
  notify:
    - reload nfs
