---
- name: install
  ansible.builtin.package:
    name: 
    - nfs-utils
    state: present
  become: true

- name: configure service
  ansible.builtin.systemd:
    name:    nfs-server
    state:   started
    enabled: yes
  become: true
